### ISSUE TITLE
Add field icons

### ISSUE THREAD

**Issue by Dan-Mihaylov** [Dan-Mihaylov/ScaryProject#3]

**Comment by mustalidhanerawala** [comment]
Can you provide a description of where do you want a field icon?

**Comment by Dan-Mihaylov** [comment]
Hello, thanks for getting in touch. This project is a task given to me from a DevOps course, I am to open, work and close the issues by myself, like a lunatic. Have a nice day.

**Comment by mustalidhanerawala** [comment]
So I can't contribute?

**Comment by mustalidhanerawala** [comment]
Because I really liked the idea and I was giving a complete makeover to you project.
